import { Button } from '@/components/ui/button';
import { Save, Download, RotateCcw } from 'lucide-react';
import { jsPDF } from 'jspdf';
import type { CompanyReport } from '@/types/research';
import { useToast } from '@/hooks/use-toast';

interface ReportActionsProps {
  report: CompanyReport;
  onSave: () => void;
  onReset: () => void;
}

export function ReportActions({ report, onSave, onReset }: ReportActionsProps) {
  const { toast } = useToast();

  const downloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let yPosition = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(`${report.companyName} (${report.ticker})`, margin, yPosition);
      yPosition += 10;

      // Subtitle
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text(`${report.rawData.sector} • ${report.rawData.industry}`, margin, yPosition);
      yPosition += 5;
      doc.text(`Analyzed: ${new Date(report.analyzedAt).toLocaleDateString()}`, margin, yPosition);
      yPosition += 15;

      doc.setTextColor(0);

      // Overview
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Overview', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const overviewLines = doc.splitTextToSize(report.brief.overview, contentWidth);
      doc.text(overviewLines, margin, yPosition);
      yPosition += overviewLines.length * 5 + 10;

      // Business Model
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Business Model', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const businessLines = doc.splitTextToSize(report.brief.businessModel, contentWidth);
      doc.text(businessLines, margin, yPosition);
      yPosition += businessLines.length * 5 + 10;

      // Financials
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Financials', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const financialLines = doc.splitTextToSize(report.brief.financials, contentWidth);
      doc.text(financialLines, margin, yPosition);
      yPosition += financialLines.length * 5 + 10;

      // Key Risks
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Key Risks', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      report.brief.risks.forEach((risk) => {
        const riskLines = doc.splitTextToSize(`• ${risk}`, contentWidth - 5);
        doc.text(riskLines, margin + 5, yPosition);
        yPosition += riskLines.length * 5 + 2;
      });
      yPosition += 8;

      // Opportunities
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Opportunities', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      report.brief.opportunities.forEach((opp) => {
        const oppLines = doc.splitTextToSize(`• ${opp}`, contentWidth - 5);
        doc.text(oppLines, margin + 5, yPosition);
        yPosition += oppLines.length * 5 + 2;
      });
      yPosition += 10;

      // Check if we need a new page for comparables
      if (yPosition > 240) {
        doc.addPage();
        yPosition = 20;
      }

      // Comparable Companies
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Comparable Companies', margin, yPosition);
      yPosition += 10;

      report.comparables.forEach((comp, idx) => {
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(`${idx + 1}. ${comp.companyName} (${comp.ticker}) - ${comp.similarityScore}% match`, margin, yPosition);
        yPosition += 6;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Market Cap: ${comp.keyMetrics.marketCap} | P/E: ${comp.keyMetrics.peRatio}`, margin + 5, yPosition);
        yPosition += 5;
        const reasoningLines = doc.splitTextToSize(comp.reasoning, contentWidth - 10);
        doc.text(reasoningLines, margin + 5, yPosition);
        yPosition += reasoningLines.length * 5 + 8;
      });

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by MergerFlow Company Research Agent', margin, doc.internal.pageSize.getHeight() - 10);

      doc.save(`${report.ticker}-research-report.pdf`);

      toast({
        title: 'PDF Downloaded',
        description: `${report.ticker} research report saved`,
      });
    } catch (err) {
      toast({
        title: 'Download Failed',
        description: 'Unable to generate PDF',
        variant: 'destructive',
      });
    }
  };

  return (
    <div className="flex flex-wrap gap-3 pt-6 border-t border-border">
      <Button onClick={onSave} variant="default">
        <Save className="mr-2 h-4 w-4" />
        Save Report
      </Button>
      <Button onClick={downloadPDF} variant="outline">
        <Download className="mr-2 h-4 w-4" />
        Download PDF
      </Button>
      <Button onClick={onReset} variant="ghost">
        <RotateCcw className="mr-2 h-4 w-4" />
        New Analysis
      </Button>
    </div>
  );
}
